---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/12 10:28
---

local tq1a = require("Test1.TestRequire1")
local tq1b = require("Test1.TestRequire1")

print(tq1a == tq1b)

testf('asdf')
