---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/12 11:25
---

function width()
    return 10
end

function height()
    return 10
end

function logicCoord2index(x, y)
    return (x - 1) + width() * (y - 1) + 1
end

function index2logicCoord(index)
    index = index - 1
    local y = math.floor(index / width())
    local x = index % width()
    return x + 1, y + 1
end

local i34 = logicCoord2index(3,4)
print(i34)
print(index2logicCoord(i34))

local i54 = logicCoord2index(5,4)
print(i54)
print(index2logicCoord(i54))
