---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/10 18:10
---

print("abs" == "abs")

local strContent = "abs"

print(string.len(strContent))
print(string.byte(strContent,0,3))
local byteContent = string.byte(strContent,0,3)
print(type(byteContent))

print("end")

print("hello")
print(true)
