---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/12 10:42
---
local function Test1()
    local pool = {
    }

    pool[10000] = 2

    for k, v in pairs(pool) do
        print(k)
        print(v)
    end

    function a(index)
        return index + 1, index + 2, 6, 6, 6
    end

    print(type(a(1)))
    print(a(2))
    local result1, result2 = a(2)
    print(result1)
    print(result2)

    print(type({}) == "table")
end

local function Test2()
    print("test2")
    local pool = {1,2,3,a = 'a', b = 'b'}
    print("#1", #pool)
    pool[4] = 4
    pool[5] = 5
    pool[100] = 100
    table.insert(pool, 2)
    print("#2", #pool)
    for k, v in pairs(pool) do
        print(k, v)
    end
end

local function Test3()
    print("test3")
    local t3 = {a = 'a', b = 'b'}
    print(#t3)
end

local function Test4()
    local t1 = {0}
    local t2 = {}
    t2[0] = 1
    t2[1] = 1
    print(#t2)
    print(t2[1])
end

local function Test5()

    local t1 = {}
    table.insert(t1, 1)
    table.insert(t1, 2)
    table.insert(t1, 3)
    --t1[2] = nil
    print(#t1)
    for i = 1, #t1 do
        if i == 2 then
            --t1[i] = nil
            table.remove(t1, 2)
        else
            print(i, t1[i])
        end
    end
    print(#t1)
    --table.remove(t1, 2)
    --print(#t1)
end

Test5()
