---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/23 17:21
---

local a = 400 * 10000.0

local size = a * 32 / (8 * 1024 * 1024)

print(size)
